[project]
name = "DAE"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.digi-asset-ex]
path = "contracts/digi-asset-ex.clar"
depends_on = []
